CREATE TABLE SALES_ORDER_DETAIL (
    S_ORDER_NO VARCHAR2(6),
    PRODUCT_NO VARCHAR2(6),
    QTY_ORDER NUMBER(8, 0),
    QTY_DISP NUMBER(8, 0),
    PRODUCT_RATE NUMBER(10, 0),
    PRIMARY KEY (S_ORDER_NO, PRODUCT_NO),
    CONSTRAINT fk_sales_order FOREIGN KEY (S_ORDER_NO)
        REFERENCES SALESORDER (S_ORDER_NO) ENABLE,
    CONSTRAINT fk_product FOREIGN KEY (PRODUCT_NO)
        REFERENCES PRODUCT (PRODUCT_NO) ENABLE
);
