CREATE TABLE SALESORDER (
    S_ORDER_NO VARCHAR2(6),
    S_ORDER_DATE DATE,
    CLIENT_NO NUMBER(12, 0),
    SALESMAN_NO VARCHAR2(26),
    DELIVERY_TYPE CHAR(1) DEFAULT 'F',
    BILLED_YN CHAR(1),
    DELIVERY_DATE DATE,
    ORDER_STATUS VARCHAR2(10),
    CHECK (S_ORDER_NO LIKE 'O%') ENABLE,
    CHECK (DELIVERY_TYPE IN ('P', 'F')) ENABLE,
    CHECK (BILLED_YN IN ('Y', 'N')) ENABLE,
    CHECK (ORDER_STATUS IN ('IP', 'C', 'F')) ENABLE,
    PRIMARY KEY (S_ORDER_NO)
);

ALTER TABLE SALESORDER 
ADD CONSTRAINT fk_client FOREIGN KEY (CLIENT_NO)
REFERENCES CLIENT (CLIENT_NO) ENABLE;

ALTER TABLE SALESORDER 
ADD CONSTRAINT fk_salesman FOREIGN KEY (SALESMAN_NO)
REFERENCES SALESMASTER (SALESMAN_NO) ENABLE;
